//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSolicitud
    {
        public int IdDetalleSol { get; set; }
        public int IdSolicitud { get; set; }
        public int IdCurso { get; set; }
        public string Profesor { get; set; }
        public string Aula { get; set; }
        public string Sede { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
